<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="TUnit" />
    <PackageReference Include="Verify.TUnit" />
    <PackageReference Include="Argon" />
    <PackageReference Include="DiffEngine" />
    <PackageReference Include="EmptyFiles" />
    <PackageReference Include="SimpleInfoName" />
    <PackageReference Include="Verify" />
    <ProjectReference Include="..\Verify.DocNet\Verify.DocNet.csproj" />
    <PackageReference Include="ProjectDefaults" PrivateAssets="all" />

    <None Include="..\Tests\sample.pdf" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
